D(OP_SendLoginInfo)
E(OP_ApproveWorld)
E(OP_EnterWorld)
E(OP_ExpansionInfo)
E(OP_SendCharInfo)
E(OP_ZoneEntry)
E(OP_PlayerProfile)
E(OP_ZoneServerInfo)
E(OP_Weather)
E(OP_NewZone)
E(OP_NewSpawn)
E(OP_ZoneSpawns)
E(OP_SpawnDoor)
E(OP_GuildsList)
#undef E
#undef D
